### ISSUE TITLE
Type filtering

### ISSUE THREAD

**Issue by nminhtu94** [ConnektApp/node-snaking#3]
Please add type filtering (?type=all/engineer/designer/presenter) for the following API:

- [ ] GET hirings/:id/feeds
- [ ] GET users/:id/connects/up
- [ ] GET users/:id/connects/down

**Comment by yorkie** [comment]
wrong repo

**Comment by nminhtu94** [comment]
so what repo should it be in? So I can change it

**Comment by yorkie** [comment]
oh wait

**Comment by yorkie** [comment]
Ok, move the issues here: https://github.com/ConnektApp/api/issues
