### ISSUE TITLE
Fix on search API

### ISSUE THREAD

**Issue by nminhtu94** [ConnektApp/node-snaking#4]
Currently, the search API does not work for query like this:

https://connekt-api-dev2.herokuapp.com/api/users/search?q=tunguyen&name=true&access_token=0QeOI81DE6hsWFT9ae63k0BS3wi1akAwGLBwFwnzSIUkglJRVyvtiQdisK1ZqGsl

**Comment by yorkie** [comment]
wrong repo, please move to ConnektApp/api, thanks
